### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by KonstantinFromRussia** [aidsoul/vktote#1]
Приветствую!
Вот такое вот выскакивает при выполнении скрипта - что-бы это значило???
Fatal error: Maximum execution time of 60 seconds exceeded in W:\domains\bot2.ru\vendor\aidsoul\vktote\src\DataBase\Db.php on line 27

**Comment by aidsoul** [comment]
Просто увеличьте max_execution_time в php.ini. Установите его на 1800 и перезапустите Apache или любой другой сервер, который вы используете.

**Comment by KonstantinFromRussia** [comment]
Да, спасибо. Я понял. А вот такой вопрос - ограничения ВК - почитал ссылку вашу:
об ограничениях [VK api](https://dev.vk.com/api/api-requests). 
Там собственно не описано количество обращений - вы вроде говорили про 100
вот тут вот:
  	    'count'         => 5
То есть если я поставлю туда не 99 а 299 - то будут некие санкции и ограничения???
Это я к тому, что если на стене более 100 записей - то их не выкачать никаким образом- правильно?
Ставлю 99 - скрипт берет 99 записей и при следующем запуске он забирает только новые записи.
А те, что за пределом 99 - так и остаются не закачанными - правильно я понимаю?

**Comment by aidsoul** [comment]
VK разрешает получить за раз максимально 100 записей.  Если вы поставите больше 100 записей, скрипт выдаст ошибку.

> То есть если я поставлю туда не 99 а 299 - то будут некие санкции и ограничения??? Это я к тому, что если на стене более 100 записей - то их не выкачать никаким образом- правильно? Ставлю 99 - скрипт берет 99 записей и при следующем запуске он забирает только новые записи. А те, что за пределом 99 - так и остаются не закачанными - правильно я понимаю?

Получить можно абсолютно все записи со стены группы (начиная с первой), но у меня не возникало такой необходимости. Поэтому в боте, данная функция не была реализована.

**Comment by KonstantinFromRussia** [comment]
Вообще-то тема нужная и актуальная. В связи с известными событиями для жителей РФ становится  актуальной связка ВК-Телеграм.
А самым актуальным был-бы комбайн позволяющий автопостить по следующей схеме:
ВК -> Телеграм -> Wordpress или
Телеграм -> ВК -> Wordpress
или просто
ВК -> Wordpress
Телеграм ->Wordpress
В планах нет ничего такого по созданию???

**Comment by aidsoul** [comment]
Если будет свободное время, возможно сделаю. Пока в планах добавить возможность отправки видео.

**Comment by KonstantinFromRussia** [comment]
В общем опять некие проблемы.
На локалке все работает, а при попытке запустить на сайте выдает вот это:
Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'al14434_bot.Vkgroup' doesn't exist in /workspace/sites/fungoterapevt/vendor/aidsoul/vktote/src/DataBase/Vkgroup.php:24 Stack trace: #0 /workspace/sites/fungoterapevt/vendor/aidsoul/vktote/src/DataBase/Vkgroup.php(24): PDOStatement->execute(Array) #1 /workspace/sites/fungoterapevt/vendor/aidsoul/vktote/src/Telegram/Telegram.php(64): Vktote\DataBase\Vkgroup->check('prio_info') #2 /workspace/sites/fungoterapevt/vendor/aidsoul/vktote/src/Telegram/Telegram.php(80): Vktote\Telegram\Telegram->checkIfExistGroup() #3 /workspace/sites/fungoterapevt/vendor/aidsoul/vktote/src/Telegram/Telegram.php(98): Vktote\Telegram\Telegram->checkIfExistPost(811515) #4 /workspace/sites/fungoterapevt/vendor/aidsoul/vktote/src/Wall/Wall.php(90): Vktote\Telegram\Telegram->send(Array) #5 /workspace/sites/fungoterapevt/vendor/aidsoul/vktote/src/Wall/Wall.php(106): Vktote\Wall\Wall->middleBodyWall(Array) #6 /workspace/sites/fungoterapevt/vendor/aidsoul/vktote/src/Bot.php(24): Vktote\Wall\Wall->collectAndPush() #7 /workspace/sites/fungoterapevt/bot_prio-info.php(22): Vktote\Bot::start(Array) #8 {main} thrown in /workspace/sites/fungoterapevt/vendor/aidsoul/vktote/src/DataBase/Vkgroup.php on line 24

**Comment by KonstantinFromRussia** [comment]
Я так понимаю, что вроде намекается на то, что базы данных или записи нужной нет - но все нужное создано:
![free-www-1](https://user-images.githubusercontent.com/31459888/163070731-a72bb293-2073-453c-ab36-1e88e19fd5c5.jpg)

**Comment by KonstantinFromRussia** [comment]
Код самого бота в части БД вот такой:

```
    'Db'        =>[
       	'host'          => 'mysql:host=localhost',
       	'dbName'        =>  'al14434_bot',
        'user'          =>  'al14434_zzz',
        'pass'          =>  '123456'
      ],

```

Да, сделал файл test.php , вот такого содержания:

```
<?php
$servername = "localhost";
$database = "al14434_bot";
$username = "al14434_zzz";
$password = "123456";
// Создаем соединение
$conn = mysqli_connect($servername, $username, $password, $database);
// Проверяем соединение
if (!$conn) {
    die("Connection failed: " . mysqli_connect_error());
}
echo "Connected successfully";
mysqli_close($conn);
?>
```

после выполнения - ответ такой:

**Connected successfully**

То есть с базой нормально соединяется.

**Comment by KonstantinFromRussia** [comment]
Сорри, я мало понимаю в программировании - Но сами-то проверяли на реальном сервере под Линуксом а не под Виндой???
Дело в том, ято насколько я понял - для Винды запись названия таблицы **_Vkgroup и vkgroup_** - это одно и то же, а для Линукс -это две разные записи.

**Comment by KonstantinFromRussia** [comment]
Вот так вот заработало. Вам надо исправить DB.SQL
Внутри должно быть вот так:
```
CREATE TABLE Vkgroup (
  id_group int NOT NULL AUTO_INCREMENT,
  name varchar(100) NOT NULL,
  PRIMARY KEY (id_group)
);

CREATE TABLE Post (
  id_post int NOT NULL,
  group_id int NOT NULL,
  CONSTRAINT past_ibfk FOREIGN KEY (group_id) REFERENCES vkgroup (id_group)
);
```
То есть:
вместо vkgroup -> Vkgroup
вместо post -> Post

**Comment by aidsoul** [comment]
> Сорри, я мало понимаю в программировании - Но сами-то проверяли на реальном сервере под Линуксом а не под Виндой??? Дело в том, ято насколько я понял - для Винды запись названия таблицы **_Vkgroup и vkgroup_** - это одно и то же, а для Линукс -это две разные записи.

Понял в чем была ошибка, я сделал push не той ветки. 
Тестировался на Debian 11 в течении месяца. Всё работает без проблем.

**Comment by KonstantinFromRussia** [comment]
Так по итогу-то что???
Конкретный сервер - если в базе db.sql вашего приложения записи vkgroup / post - не работает
если записи Vgroup/Post - работает.
Вижу час назад обновили репозиторий, но вижу что в db.sql - названия не поменялись.
Сорри - а что поменялось?

**Comment by aidsoul** [comment]
> Так по итогу-то что??? Конкретный сервер - если в базе db.sql вашего приложения записи vkgroup / post - не работает если записи Vgroup/Post - работает. Вижу час назад обновили репозиторий, но вижу что в db.sql - названия не поменялись. Сорри - а что поменялось?

Теперь не нужно менять название таблицы на заглавные буквы.
