### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by energen22** [aidsoul/vktote#21]
Здравствуйте, а как запустить в браузере, без крона.

**Comment by aidsoul** [comment]
Здравствуйте. Можно создать файл в корне, к примеру: test.php
```
<?php
if($_GET['group'] && !empty($_GET['group']))
{
    $argv[1] = $_GET['group'];
    include 'groups/start.php';
}else{
    echo 'Ошибка';
}
```
И к нему обращаться через адресную строку: http://домен/test.php?group=название_группы

**Comment by energen22** [comment]
Спасибо. Это гениально. Добавьте пожалуйста в readme, может кому-нибудь пригодится.

**Comment by energen22** [comment]
Только вот теперь ошибки
![image](https://user-images.githubusercontent.com/118126815/201862278-de9b7919-387e-421f-b691-0c3fd8a38b30.png)

**Comment by energen22** [comment]
Здравствуйте.
Подскажите пожалуйста в чем может быть ошибка.

**Comment by energen22** [comment]
![image](https://user-images.githubusercontent.com/118126815/201871347-a45b38ee-4365-4a09-8029-e8a50369acec.png)

каналы теперь только формата @channel

**Comment by aidsoul** [comment]
Здравствуйте, у себя проверил, всё работает исправно. 
"chatId" должен начинаться с "-". К примеру: chatId="-435654235".

**Comment by energen22** [comment]
да так и есть.
![image](https://user-images.githubusercontent.com/118126815/201875029-beefdedb-a5f2-4128-badf-e0d30a2e4ad8.png)
но вылетает ошибка.

**Comment by energen22** [comment]
что в константе дело, а именно в ID канала.

**Comment by aidsoul** [comment]
Попробуйте убрать "@" в поле "botName".

**Comment by aidsoul** [comment]
#22 
Теперь можно запустить группу с помощью GET-запроса
https://domain/api/bot.start?group=group_name

> Здравствуйте, а как запустить в браузере, без крона.

**Comment by smetanov** [comment]
vk token  какой нужен? От группы с которой посты брать или токен владельца группы? Вообщем при указании токена владельца постинг идет со стены владельца ,а не с группы указаной в настройках. При токене группы выдает ошибку и ничего не постит.

```
Warning: Undefined array key "response" in C:\OSPanel\domains\localhost\app\Vk\Wall\Wall.php on line 49

Warning: Trying to access array offset on value of type null in C:\OSPanel\domains\localhost\app\Vk\Wall\Wall.php on line 49

Warning: foreach() argument must be of type array|object, null given in C:\OSPanel\domains\localhost\app\Vk\Wall\Wall.php on line 49
404 Page Not Found
```

Я в замешательстве :) прошу помощи ;)
